spring:
  profiles:
    active: dev
  application:
    name: employee_management
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  cache:
    type: simple
    cache-names: totalEmployees
    caffeine:
      spec: expireAfterWrite=1m

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
