spring:
  profiles:
    active: dev
  application:
    name: employee_management
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  cache:
    type: simple
    cache-names: totalEmployees
    caffeine:
      spec: expireAfterWrite=1m

security:
  jwt:
    secret: abcdefghijklmnopqrstuvwxyz123456789!@#$%^&*()
    expiration: 864000

management:
  endpoints:
    web:
      exposure:
        include:
          include:
            - health
            - metrics
